name: Build a draft release

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.actor != 'dependabot[bot]' }} && ${{ github.actor != 'renovate[bot]' }}  
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Retrieve app name & assets from config
        run: |
          APPNAME=$(jq -r '.name' "release.json")
          echo "APPNAME=$APPNAME" >> $GITHUB_ENV
          URLS=$(jq -r '.externalAssets[].url' "release.json")

          for URL in $URLS; do
              FILENAME=$(basename "$URL")
              # Perform desired operations with the URL
              # Example: Download the file
              curl -L -o "./assets/$FILENAME" "$URL"
          done
        
      - name: Draft a release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELVER }}
          body: |
            **!Important - review then remove this top section**

            - [ ] Verify the resources from /assets are attached correctly to this release
            - [ ] Set the tag to a semver matching the release (e.g. `v1.9.3`)
            - [ ] Add any comments on breaking changes/ amends to the auto generated release notes below
            - [ ] Delete this section

            We are pleased to release ${{ env.APPNAME }}. Assets are attached to this release for your convenience.

            ## What's Changed
            
            The following changes have been made for this release:
            
            - Change 1.
            - Change 2.
            - Change 3.

          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./assets/*
            
